# Задание 1
Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

1)если источник traffic_source равен yandex или google, то в source_type ставится organic

2)для источников paid и email из России - ставим ad

3)для источников paid и email не из России - ставим other

4)все остальные варианты берем из traffic_source без изменений

In [23]:
import pandas as pd
log_ = pd.read_csv('visit_log.csv', sep=';')

def source_type(row):
    if row['traffic_source'] in ['yandex', 'google']:
        return 'organic'
    elif row['traffic_source'] in ['paid', 'email']:
        return 'ad' if row['region'] == 'Russia' else 'other'
    else: 
        return row['traffic_source']

log_['source_type'] = log_.apply(source_type, axis = 1)

log_.tail(8)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
18930,1550094269,f1b4590410,https://host.ru/a5dda93e70318570c0,Russia,7f59a1e6a7,direct,direct
18931,1550094269,a7e2dfd759,https://host.ru/ef57543002ce2a0f2a,Belarus,04fec64cda,direct,direct
18932,1550094280,5001544772,https://host.ru/9f90e5c423a5f976d4,Russia,072148e3ba,google,organic
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,other
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,ad
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,organic
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,ad
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,ad

# Задание 2
В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:

1) Прочитайте содержимое файла с датафрейм

2) Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [32]:
url = pd.read_csv('URLs.txt')
url[url.url.str.contains(('.*\/\d{8}-.*'))].head(8)

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
10  /middleeast/36131117-divizion-s-400-ne-zametil...
11  /economics/36065674-rossiyane-vozmutilis-minim...
12  /politics/36118047-otets-24-detey-potreboval-i...

# Задание 3
В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [33]:
from pymystem3 import Mystem

In [36]:
%%time
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

m = Mystem()

def lemms(row):
        lemmas = m.lemmatize(row['keyword'])
        return str(''.join(lemmas).strip())
        
data['lemmas'] = data.apply(lemms, axis=1)
data

Wall time: 3.39 s

                 keyword   shows               lemmas
0    курс гривны к рублю  125076  курс гривна к рубль
1        доллары в рубли  114173       доллар в рубль
2  100 долларов в рублях   97534   100 доллар в рубль
3             курс рубля   53546           курс рубль